### ISSUE TITLE
Can I learn more source code about your experiments？

### ISSUE THREAD

**Issue by YefanWu** [anonymousheliks23/heliks#2]
I am working on a Cheetah-optimization project, which approach a similar performance speedup to what HELiks had reported on CCS'23, on our AMD EPYC 7B12 machine. 

Therefore, we want to make a performance evaluation over various network, like SqNet and Resnet50. I tried to merge your code into the framework of CryptFlow2 to perform inference on CNN, but SEAL just throws various exceptions (e.g, run out of modulus chain). So I am just trying to ask, if there were any merged code that avilable for open source？

**Comment by shashankballa** [comment]
The open-sourced code in this repository is only meant for evaluating the linear operations. Please read through the "FCField::matrix_multiplication" function at https://github.com/shashankballa/HELiKs/blob/e337f3779d34ddc5bcf9a8eaf6b9ec993d2bc098/SCI/src/LinearHE/fc-field.cpp#L1038.

You may use this, a similar implementation for convolution, and the provided testing scripts to optimize your selection of the HE modulus chain. The defaults provided have been optimized only for the selected plaintext modulus. In case you need to work with a different HE plaintext modulus you must optimize other HE parameters.

If you choose to run a whole NN, notice from the aforementioned script that the NTT pre-processing on the weights will be performed on the fly if you run the NN using the default cryptflow compiler. In order to be faithful to the paper you must modify the workflow such that the weights are encoded, NTT transformed and written to a file locally while offline. When online, on receiving a query, the NTT transformed weights must be read from memory when the corresponding layer is being computed.
